version: '3.3'

services:
  db:
    image: mysql/mysql-server:latest-aarch64
    platform: linux/arm64/v8
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog"

  admin:
    depends_on:
      - db
    links: 
      - db
    restart: on-failure
    build:
      context: .    
    command: "/bin/admin -migrate"
    environment:
      ADMIN_DBUSER: "root"
      ADMIN_DBPASS: "root"
      ADMIN_DBHOST: "db"
      ADMIN_DBNAME: "blog"

  site:
    depends_on:
      - db
    links: 
      - db
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
    command: "/bin/globber"
    volumes:
      - ./templates/html:/templates/html
    environment:
      GLOBBER_DBUSER: "root"
      GLOBBER_DBPASS: "root"
      GLOBBER_DBHOST: "db"
      GLOBBER_DBNAME: "blog"
      GLOBBER_SITENAME: "SqweebNet"
      GLOBBER_TOKENSECRET: "THISISNOTASECRET"
      GLOBBER_MINECRAFTHOST: "play.penguincraft.io"

