version: '3.3'

services:
  db:
    # logging:
    #   driver: none
    image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "bloguser"
      MYSQL_PASS: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog"

  admin:
    depends_on:
      - db
    links: 
      - db
    restart: on-failure
    build:
      context: .    
    command: "/bin/admin -migrate"
    environment:
      ADMIN_DBUSER: "root"
      ADMIN_DBPASS: "root"
      ADMIN_DBHOST: "db"
      ADMIN_DBNAME: "blog"

  site:
    depends_on:
      - db
    links: 
      - db
    build:
      context: .
    ports:
      - 3000:3000
    restart: always
    command: "/bin/globber"
    environment:
      GLOBBER_DBUSER: "root"
      GLOBBER_DBPASS: "root"
      GLOBBER_DBHOST: "db"
      GLOBBER_DBNAME: "blog"
      GLOBBER_SITENAME: "SqweebNet"
      GLOBBER_TOKENSECRET: "THISISNOTASECRET"
      GLOBBER_MINECRAFTHOST: "sqweeb.net"

volumes:
    db_data: {}
